package eu.gridverse.srv.rsa.services.config;
import eu.gridverse.infra.event.EventPublisherService; import eu.gridverse.infra.metadata.MetadataRepository; import eu.gridverse.powsbl.network.NetworkUpdateAdapter; import eu.gridverse.srv.rsa.services.workflow.*; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import javax.sql.DataSource; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.autoconfigure.condition.*; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.jdbc.datasource.DriverManagerDataSource; import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry; import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
@Configuration public class RsaConfiguration implements WebMvcConfigurer {
    @Bean @ConditionalOnProperty("gridverse.metadata.jdbc-url") DataSource workflowDataSource(@Value("${gridverse.metadata.jdbc-url}")String url,@Value("${gridverse.metadata.username:gridverse}")String username,@Value("${gridverse.metadata.password:gridverse-local}")String password){DriverManagerDataSource source=new DriverManagerDataSource(url,username,password);source.setDriverClassName("org.postgresql.Driver");return source;}
    @Bean @ConditionalOnProperty("gridverse.metadata.jdbc-url") MetadataRepository<WorkflowMetadata, UUID> jdbcWorkflowMetadataRepository(DataSource dataSource){return new JdbcWorkflowMetadataRepository(new JdbcTemplate(dataSource));}
    @Bean @ConditionalOnMissingBean MetadataRepository<WorkflowMetadata, UUID> workflowMetadataRepository() { return new MetadataRepository<>() { private final Map<UUID, WorkflowMetadata> values = new ConcurrentHashMap<>(); public WorkflowMetadata save(WorkflowMetadata value) { values.put(value.id(), value); return value; } public Optional<WorkflowMetadata> findById(UUID id) { return Optional.ofNullable(values.get(id)); } }; }
    @Bean @ConditionalOnMissingBean EventPublisherService rsaEventPublisherService() { return (topic, key, event) -> { }; }
    @Bean RsaWorkflowService rsaWorkflowService(NetworkUpdateAdapter networks, MetadataRepository<WorkflowMetadata, UUID> metadata, EventPublisherService events) { return new RsaWorkflowService(networks, metadata, events); }
    @Override public void addResourceHandlers(ResourceHandlerRegistry registry){registry.addResourceHandler("/openapi/**").addResourceLocations("classpath:/openapi/");}
}
