spring:
  config:
    import:
      - classpath:base/srv.cnm.services-application.yml
      - classpath:base/srv.cnm.services-infra.yml
      - optional:classpath:local/srv.cnm.services-application.yml
