package eu.gridverse.infra.storage.document.elasticsearch;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.*; import eu.gridverse.infra.storage.document.*; import java.net.URI; import java.net.http.*; import java.util.*;
public final class ElasticsearchDocumentRepository implements DocumentRepositoryService {
    private final URI base; private final ObjectMapper json; private final HttpClient http=HttpClient.newHttpClient(); public ElasticsearchDocumentRepository(String baseUrl,ObjectMapper json){this.base=URI.create(baseUrl.endsWith("/")?baseUrl:baseUrl+"/");this.json=json;}
    public <T>T save(String index,String id,T document){send("PUT",index+"/_doc/"+encode(id),write(document));return document;}
    public <T>Optional<T> find(String index,String id,Class<T> type){HttpResponse<String> r=send("GET",index+"/_doc/"+encode(id),null);if(r.statusCode()==404)return Optional.empty();try{return Optional.of(json.treeToValue(json.readTree(r.body()).path("_source"),type));}catch(Exception e){throw new IllegalStateException("Elasticsearch response mapping failed",e);}}
    public <T>List<T> search(String index,DocumentSearchRequest request,Class<T> type){ObjectNode body=json.createObjectNode();body.put("from",request.page()*request.size());body.put("size",request.size());ArrayNode filters=body.putObject("query").putObject("bool").putArray("filter");request.filters().forEach((k,v)->filters.addObject().putObject("term").set(k,json.valueToTree(v)));HttpResponse<String> r=send("POST",index+"/_search",body.toString());try{List<T> values=new ArrayList<>();for(JsonNode hit:json.readTree(r.body()).path("hits").path("hits"))values.add(json.treeToValue(hit.path("_source"),type));return values;}catch(Exception e){throw new IllegalStateException("Elasticsearch search mapping failed",e);}}
    private HttpResponse<String> send(String method,String path,String body){try{HttpRequest.Builder b=HttpRequest.newBuilder(base.resolve(path)).header("content-type","application/json");b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(body));HttpResponse<String> r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()>=400&&r.statusCode()!=404)throw new IllegalStateException("Elasticsearch returned "+r.statusCode()+": "+r.body());return r;}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("Elasticsearch request interrupted",e);}catch(java.io.IOException e){throw new IllegalStateException("Elasticsearch request failed",e);}}
    private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException("document is not serializable",e);}}
    private static String encode(String value){return java.net.URLEncoder.encode(value,java.nio.charset.StandardCharsets.UTF_8);}
}
